# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: config setting.xml
      uses: whelk-io/maven-settings-xml-action@v10
      with:
        repositories: '[{ "id": "geek-snapshots", "name": "Ali Private Snapshot Repository", "url": "https://packages.aliyun.com/maven/repository/2012569-snapshot-C6Wvk0/", "releases": { "enabled": "false" }, "snapshots": { "enabled": "true" } },{ "id": "geek-releases", "name": "Ali Private Release Repository", "url": "https://packages.aliyun.com/maven/repository/2012569-release-howX4t/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
        servers: '[{ "id": "geek-snapshots", "username": "${{ secrets.GEEK_REPO_USERNAME }}", "password": "${{ secrets.GEEK_REPO_SECRET }}" }]'
    - name: Deploy to aliyun
      run: mvn -B deploy -P geek --file pom.xml
